name: Build APK
on: [push]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Tools
        run: pip install flet supabase
      - name: Build
        run: flet build apk --project "Tahmasb's Law of IMPOSSIBILITY"
      - uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: build/apk/*.apk
